export { registerGatewayWebSocket } from "./server.js";
export {
	ClientMessageSchema,
	ServerMessageSchema,
} from "./protocol.js";
export type {
	ClientMessage,
	ServerMessage,
	ChatSend,
	ContextInspect,
	UsageQuery,
	SessionList,
	ChatRouteConfirm,
	MemorySearch,
	ThreadCreate,
	ThreadList,
	ThreadUpdate,
	PromptSet,
	PromptList,
	ToolApprovalResponse,
	PreflightApproval,
	ChatStreamStart,
	ChatStreamDelta,
	ChatStreamEnd,
	ContextInspection,
	UsageReport,
	ErrorMessage,
	SessionCreated,
	SessionListResponse,
	MemorySearchResult,
	ThreadCreated,
	ThreadListResult,
	ThreadUpdated,
	PromptSetResult,
	PromptListResult,
	ToolCallNotify,
	ToolResultNotify,
	ToolApprovalRequest,
	PreflightChecklist,
} from "./protocol.js";
export {
	initConnection,
	getConnectionState,
	markStreaming,
	clearStreaming,
	isStreaming,
	removeConnection,
} from "./connection.js";
